// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Home() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<head><script src=\"//unpkg.com/alpinejs\" defer></script><script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script></head><div x-data=\"{ imageUrl: null, fileName: null }\"><label for=\"image\">Choose an image to extract the color palette from:</label> <input type=\"file\" id=\"image\" name=\"image\" accept=\"image/png, image/jpeg\" x-ref=\"inputImage\" @change=\"\n                const file = $event.target.files[0];\n                if (file) {\n                    fileName = file.name;\n                    imageUrl = URL.createObjectURL(file);\n                } else {\n                    fileName = null;\n                    imageUrl = null;\n                }\n            \"><!-- Display selected file name --><div x-show=\"fileName\" x-text=\"'Selected: ' + fileName\" class=\"text-sm text-gray-600 mt-2\"></div><!-- Display the image preview --><div x-show=\"imageUrl\" class=\"mt-4\"><img :src=\"imageUrl\" alt=\"Selected image preview\" class=\"max-w-md max-h-64 object-contain border rounded shadow-sm\"></div><!-- Optional: Clear button --><button x-show=\"imageUrl\" @click=\"\n                imageUrl = null; \n                fileName = null; \n                $refs.inputImage.value = '';\n            \" type=\"button\" class=\"mt-2 px-4 py-2 bg-red-500 text-white rounded hover:bg-red-600\">Clear Image</button></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
